include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "android/**"
    - "ios/**"
    - "macos/**"
    - "**/.fvm/**"
    - "**/current/**"
    - "current/**"
    - "current"
    - "**/*.xml"
    - "**/*.yml"
    - "**/*.yaml"
    - "bin/cache/**"
    - "build/**"
    - "lib/l10n/*.p.dart"
    - ".idea/**"
    - ".direnv/**"
    - "fastlane/**"
    - "test_driver/**"
  errors:
    annotate_overrides: info
    always_declare_return_types: info

linter:
  rules:
    annotate_overrides: info
    always_declare_return_types: info
