name: country_provider2
version: 1.0.2+1
homepage: https://github.com/ericmartineau/country_provider
description: The plugin provides several methods to fetch countries info, Apply filter, and perform search operations.
environment: 
  sdk: '>=2.14.0 <3.0.0'
dependencies: 
  http: ^0.13.4
  flutter: 
    sdk: flutter
dev_dependencies: 
  lints: ^1.0.1
  flutter_lints: ^1.0.4
  flutter_test: 
    sdk: flutter
flutter: null
